"""Tests for artifact persistence, especially the standalone PoC emission."""

from __future__ import annotations

from cvehunter import artifacts


def _redirect_dirs(monkeypatch, tmp_path):
    monkeypatch.setattr(artifacts.settings, "artifact_dir", tmp_path / "artifacts")
    monkeypatch.setattr(artifacts.settings, "pocs_dir", tmp_path / "pocs")


def test_save_artifacts_writes_verified_poc(
    tmp_path,
    monkeypatch,
    sample_exploit_result_success,
    sample_exploit_recipe,
    sample_environment_spec,
):
    _redirect_dirs(monkeypatch, tmp_path)
    state = {
        "exploit_result": sample_exploit_result_success,
        "exploit_recipe": sample_exploit_recipe,
        "environment": sample_environment_spec,
        "status": "judged",
    }
    out = artifacts.save_artifacts("CVE-2021-44228", state)

    # A copy lives in the per-run artifact bundle...
    assert (out / "poc.py").exists()
    # ...and the headline deliverable lands in pocs/<CVE>.py.
    poc = tmp_path / "pocs" / "CVE-2021-44228.py"
    assert poc.exists()

    text = poc.read_text()
    assert text.startswith("#!/usr/bin/env python3")
    assert "generated by CVEHunter" in text
    assert "Flag captured: yes" in text  # success fixture → verified PoC
    assert "pocs/CVE-2021-44228.py" in text  # usage references the CVE-named file
    assert "TARGET_HOST" in text
    assert "requests" in text  # the actual generated exploit code is embedded


def test_save_artifacts_writes_best_attempt_poc_when_not_captured(
    tmp_path, monkeypatch, sample_exploit_result_failure
):
    _redirect_dirs(monkeypatch, tmp_path)
    state = {"exploit_result": sample_exploit_result_failure, "status": "judged"}
    artifacts.save_artifacts("CVE-2021-44228", state)

    poc = tmp_path / "pocs" / "CVE-2021-44228.py"
    assert poc.exists()
    assert "best generated attempt" in poc.read_text()


def test_save_artifacts_no_poc_without_exploit_result(tmp_path, monkeypatch):
    _redirect_dirs(monkeypatch, tmp_path)
    artifacts.save_artifacts("CVE-2021-44228", {"status": "judged_partial"})
    assert not (tmp_path / "pocs" / "CVE-2021-44228.py").exists()
