"""Tests for artifact persistence, especially the standalone PoC emission."""

from __future__ import annotations

from cvehunter import artifacts


def test_save_artifacts_writes_verified_poc(
    tmp_path,
    monkeypatch,
    sample_exploit_result_success,
    sample_exploit_recipe,
    sample_environment_spec,
):
    monkeypatch.setattr(artifacts.settings, "artifact_dir", tmp_path)
    state = {
        "exploit_result": sample_exploit_result_success,
        "exploit_recipe": sample_exploit_recipe,
        "environment": sample_environment_spec,
        "status": "judged",
    }
    out = artifacts.save_artifacts("CVE-2021-44228", state)

    poc = out / "poc.py"
    assert poc.exists()
    text = poc.read_text()
    assert text.startswith("#!/usr/bin/env python3")
    assert "generated by CVEHunter" in text
    assert "Flag captured: yes" in text  # success fixture → verified PoC
    assert "USAGE" in text and "TARGET_HOST" in text
    # The actual generated exploit code is embedded (success fixture uses requests).
    assert "requests" in text


def test_save_artifacts_writes_best_attempt_poc_when_not_captured(
    tmp_path, monkeypatch, sample_exploit_result_failure
):
    monkeypatch.setattr(artifacts.settings, "artifact_dir", tmp_path)
    state = {"exploit_result": sample_exploit_result_failure, "status": "judged"}
    out = artifacts.save_artifacts("CVE-2021-44228", state)

    poc = out / "poc.py"
    assert poc.exists()
    assert "best generated attempt" in poc.read_text()


def test_save_artifacts_no_poc_without_exploit_result(tmp_path, monkeypatch):
    monkeypatch.setattr(artifacts.settings, "artifact_dir", tmp_path)
    out = artifacts.save_artifacts("CVE-2021-44228", {"status": "judged_partial"})
    assert not (out / "poc.py").exists()
