"""Artifact persistence — saves pipeline outputs to disk."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from cvehunter.config import settings

_ARTIFACT_KEYS = {
    "cve_package": "cve_package.json",
    "exploit_recipe": "exploit_recipe.json",
    "environment": "environment_spec.json",
    "exploit_result": "exploit_result.json",
    "judgement": "judgement_report.json",
}


def _select_poc_code(exploit_result: Any) -> tuple[str, bool] | None:
    """Return ``(poc_code, captured)`` — the verified PoC if the flag was captured,
    otherwise the best (longest viable) generated attempt. ``None`` if no code."""
    if exploit_result is None:
        return None
    final = (getattr(exploit_result, "final_exploit_code", "") or "").strip()
    if final:
        return final, True
    attempts = getattr(exploit_result, "attempts", []) or []
    candidates = [a.exploit_code for a in attempts if (a.exploit_code or "").strip()]
    if not candidates:
        return None
    return max(candidates, key=len), False


def _write_poc(out_dir: Path, cve_id: str, state: dict[str, Any]) -> Path | None:
    """Emit a standalone, runnable ``poc.py`` (the exploit as a reusable script).

    Written on every run that produced exploit code — not just on flag capture —
    so the generated PoC is usable directly against a test environment.
    """
    selected = _select_poc_code(state.get("exploit_result"))
    if selected is None:
        return None
    code, captured = selected

    recipe = state.get("exploit_recipe")
    env = state.get("environment")
    vuln_type = getattr(recipe, "vulnerability_type", "") if recipe else ""
    attack_vector = getattr(recipe, "attack_vector", "") if recipe else ""
    flag_location = getattr(env, "flag_location", "") if env else ""
    services = getattr(env, "services", []) if env else []
    default_target = services[0] if services else "<target-host>"

    captured_note = (
        "yes — verified: captured on the vulnerable env and FAILS on the patched env"
        if captured
        else "no — best generated attempt; adapt as needed"
    )
    poc_name = f"{cve_id}.py"
    header = "\n".join(
        [
            "#!/usr/bin/env python3",
            f"# PoC for {cve_id} — generated by CVEHunter",
            f"# Vulnerability: {vuln_type or 'unknown'}"
            + (f" ({attack_vector})" if attack_vector else ""),
            f"# Proof: reads {flag_location or 'the target secret'} from the target",
            f"# Flag captured: {captured_note}",
            "#",
            "# USAGE — run against YOUR OWN test environment.",
            f"#   This was generated for a CVEHunter sandbox target named '{default_target}'.",
            "#   Point it at your lab via TARGET_HOST / TARGET_PORT env vars or argv if",
            "#   the script reads them, otherwise edit the target near the top. The target",
            "#   must be the vulnerable build for this CVE.",
            f"#     python pocs/{poc_name} <host> <port>",
            f"#     TARGET_HOST=10.0.0.5 TARGET_PORT=8080 python pocs/{poc_name}",
            "#",
            "",
            "",
        ]
    )
    body = code.lstrip("\n")
    if body.startswith("#!"):  # drop the generated script's own shebang
        body = body.split("\n", 1)[1] if "\n" in body else ""
    poc_text = header + body

    # Keep a copy inside the per-run artifact bundle...
    (out_dir / "poc.py").write_text(poc_text)
    # ...and drop the headline deliverable into the flat pocs/<CVE>.py collection.
    pocs_dir = settings.pocs_dir
    pocs_dir.mkdir(parents=True, exist_ok=True)
    poc_path = pocs_dir / poc_name
    poc_path.write_text(poc_text)
    return poc_path


def save_artifacts(cve_id: str, state: dict[str, Any]) -> Path:
    """Write all pipeline artifacts for a CVE run to the artifact directory."""
    out_dir = settings.artifact_dir / cve_id
    out_dir.mkdir(parents=True, exist_ok=True)

    for key, filename in _ARTIFACT_KEYS.items():
        obj = state.get(key)
        if obj is None:
            continue
        data = (
            obj.model_dump_json(indent=2)
            if hasattr(obj, "model_dump_json")
            else json.dumps(obj, indent=2, default=str)
        )
        (out_dir / filename).write_text(data)

    _write_poc(out_dir, cve_id, state)

    (out_dir / "run_metadata.json").write_text(
        json.dumps(
            {
                "cve_id": cve_id,
                "status": state.get("status"),
                "total_cost_usd": state.get("total_cost_usd", 0.0),
                "errors": state.get("errors", []),
            },
            indent=2,
        )
    )

    return out_dir
